[site]
title = "Sportfest 2023: Auswertung der Ergebnisse"

[header]
title = "Sportfest 2023 &ndash; Auswertung"

[main]
title = "Ergebnisse nach Klassenstufen"

[footer]
copyright_notice = "&copy; 2023 Team IT-Auswertung"
