# Generated by Django 4.2.3 on 2023-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(verbose_name='Klassenstufe')),
                ('parallel_class', models.CharField(max_length=1, verbose_name='Parallelklasse')),
            ],
            options={
                'verbose_name': 'Klasse',
                'verbose_name_plural': 'Klassen',
            },
        ),
    ]
