# Generated by Django 4.2.3 on 2023-07-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sport',
            field=models.CharField(max_length=50, verbose_name='Sportart'),
        ),
    ]
