# Generated by Django 4.2.3 on 2023-07-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_station_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Punktzahl')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.class', verbose_name='Klasse')),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Wertung',
                'verbose_name_plural': 'Wertungen',
            },
        ),
    ]
