# Generated by Django 4.2.3 on 2023-07-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['class_name'], 'verbose_name': 'Klasse', 'verbose_name_plural': 'Klassen'},
        ),
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='1a', max_length=3, unique=True, verbose_name='Klasse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Punktzahl'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_level',
            field=models.PositiveIntegerField(verbose_name='Klassenstufe'),
        ),
    ]
