# Generated by Django 4.2.3 on 2023-07-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_class_options_class_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='class',
            name='parallel_class',
        ),
    ]
