# Generated by Django 4.2.3 on 2023-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_class_class_level_remove_class_parallel_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sport',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sportart'),
        ),
    ]
